Remove hardocded pagerduty APIURL
grafana/terraform-provider-grafana pull request #1576
Opened 2024-05-20 15:48 UTC by gaurav1999

- Fixes: https://github.com/grafana/grafana/issues/82741
- Linked PR: https://github.com/grafana/grafana/pull/88007

Mentioned by @yuri-tceretian here on the PR: https://github.com/grafana/grafana/pull/88007#issuecomment-2120646920

Thanks!  🚀

2024-05-21 12:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/terraform-provider-grafana?pullRequest=1576) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/terraform-provider-grafana?pullRequest=1576) before we can accept your contribution.<br/><hr/>**Gaurav Agrawal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/terraform-provider-grafana?pullRequest=1576) it.</sub>

2024-05-21 14:39 UTC, julienduchesne commented on internal/resources/grafana/resource_alerting_contact_point_notifiers.go
> +	r.Schema["url"] = &schema.Schema{
It needs to be used in the `pack` and `unpack` functions

2024-05-21 14:40 UTC, yuri-tceretian requested changes
@gaurav1999 thanks for opening PR. Please add packing and unpacking. You can use commit https://github.com/grafana/terraform-provider-grafana/pull/1060/commits/3da42eb0bbd3d7ff5048cd82a7fb718e3eb94908 as example. 

To update documentation you only need to run `go generate` in the root of the repository.

2024-05-21 15:45 UTC, gaurav1999 commented
> @gaurav1999 thanks for opening PR. Please add packing and unpacking. You can use commit [3da42eb](https://github.com/grafana/terraform-provider-grafana/commit/3da42eb0bbd3d7ff5048cd82a7fb718e3eb94908) as example.
> 
> To update documentation you only need to run `go generate` in the root of the repository.

Thanks @yuri-tceretian , done

However if u see my previous commit, I indeed ran go generate in the root repo, it ended up removing summary from lots of doc files, i don't understand why then @julienduchesne added a commit to fix it, so I think for now the pointers are closed, let me know if anything else is needed, thanks a lot for guiding me around on this small steps!

2024-05-21 15:46 UTC, gaurav1999 commented
Wait, I ended up adding my work email here, let me see if I can update that in commits.

2024-05-21 15:51 UTC, gaurav1999 commented
> Wait, I ended up adding my work email here, let me see if I can update that in commits.

Done

2024-05-22 01:18 UTC, julienduchesne approved these changes
LGTM! Thanks!

2024-05-22 01:18 UTC, merged