adds Sigv4 support
grafana/terraform-provider-grafana pull request #247
Opened 2021-07-23 11:33 UTC by mhausenblas

This PR addresses #193, adding Sigv4 support for the Prometheus data source.

2021-07-24 00:03 UTC, trotttrotttrott requested changes
Looks great, just some tidying up to do:

1. Run `go fmt ./grafana/`
2. Run `go generate` - this will update docs/. The content in this directory is generated from schema descriptions and example files. If you'd like to keep the example you added, add it [here](https://github.com/grafana/terraform-provider-grafana/blob/master/examples/resources/grafana_data_source/resource.tf) first. Be sure to also run `terraform fmt` on that file.

2021-07-24 00:03 UTC, trotttrotttrott commented on grafana/resource_data_source_test.go
> +	            sigv4_region    = "eu-west-1"
Whitespace is a bit wonky here.
```suggestion
				sigv4_auth   = true
				sigv4_auth_type = "default"
				sigv4_region    = "eu-west-1"

```

2021-07-26 07:38 UTC, mhausenblas commented
Thanks a lot for speedy feedback @trotttrotttrott and will do as you advised (not sure why the `go fmt` didn't happen automatically since that's how I've configured it but clearly there is a problem indeed).

2021-07-26 08:55 UTC, mhausenblas commented
OK, @trotttrotttrott I think I now did address all your points, PTAL again?

2021-07-26 19:38 UTC, trotttrotttrott commented on docs/resources/data_source.md
> +   }
`terraform fmt`...

```suggestion
  type = "prometheus"
  name = "amp"
  url  = "https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-1234567890/"

  json_data {
    http_method     = "POST"
    sigv4_auth      = true
    sigv4_auth_type = "default"
    sigv4_region    = "eu-west-1"
  }
```

2021-07-26 19:38 UTC, trotttrotttrott commented on examples/resources/grafana_data_source/resource.tf
> +   }
```suggestion
  type = "prometheus"
  name = "amp"
  url  = "https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-1234567890/"

  json_data {
    http_method     = "POST"
    sigv4_auth      = true
    sigv4_auth_type = "default"
    sigv4_region    = "eu-west-1"
  }
```

2021-07-26 19:43 UTC, trotttrotttrott commented on docs/resources/data_source.md
`tfplugindocs` wants this space here. Adding back so `go generate` doesn't produce a diff.

```suggestion


```

2021-07-26 19:45 UTC, trotttrotttrott approved these changes

2021-07-26 19:46 UTC, merged