Adding token as a parameter for Flux version
grafana/terraform-provider-grafana pull request #690
Opened 2022-10-19 14:50 UTC by arielpardomartin

2022-10-19 14:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/terraform-provider-grafana?pullRequest=690) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/terraform-provider-grafana?pullRequest=690) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/terraform-provider-grafana?pullRequest=690) it.</sub>

2022-10-19 15:15 UTC, inkel requested changes

2022-10-19 15:15 UTC, inkel commented on grafana/resource_data_source.go
> +		Token:    		   d.Get("secure_json_data.0.sigv4_token").(string),
Please run `go fmt` in the top level directory to fix the formatting errors.

2022-11-11 01:54 UTC, julienduchesne commented
I will close this. This is already possible as described here: https://github.com/grafana/terraform-provider-grafana/issues/691#issuecomment-1311128637

The `json_data` and `secure_json_data` fields are deprecated

2022-11-11 01:54 UTC, closed without merging