New `data_source_role` resource
grafana/terraform-provider-grafana pull request #917
Opened 2023-05-16 07:12 UTC by skatsaounis

Adds new `data_source_role ` resource which fetches RBAC roles by name.

Relevant Go Client PR: https://github.com/grafana/grafana-api-golang-client/pull/151

2023-05-16 07:18 UTC, skatsaounis commented on go.sum
> -github.com/grafana/grafana-api-golang-client v0.21.0 h1:PQ2Wfo9jMMiftC4VRMlJxbUNvYCXMV1YFDKm7Ny3SaM=
Will revert when Go client PR is merged

2023-05-16 07:18 UTC, skatsaounis commented on go.mod
> +
Will revert when Go client PR is merged

2023-06-01 07:04 UTC, skatsaounis commented
@inkel I update the PR with the new client version and it is ready to be reviewed.

2023-06-01 12:30 UTC, inkel requested changes
CI is failing because it's missing the `go.sum` updated entry for the Grafana Go client. By looking at the list of changed files it seems you forgot to include it in your last commit, please add it and I'll happily review the PR.

2023-06-02 14:12 UTC, skatsaounis commented
@inkel I think we are good to go now. I tried to rebase and fix conflicts and somehow I messed up `go.sum`. Please take a look

2023-07-05 00:31 UTC, julienduchesne approved these changes
LGTM!

2023-07-05 00:31 UTC, merged